//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class datacenterEntities : DbContext
    {
        public datacenterEntities()
            : base("name=datacenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sice_candidatos> sice_candidatos { get; set; }
        public DbSet<sice_candidaturas> sice_candidaturas { get; set; }
        public DbSet<sice_casillas> sice_casillas { get; set; }
        public DbSet<sice_distritos_locales> sice_distritos_locales { get; set; }
        public DbSet<sice_municipios> sice_municipios { get; set; }
        public DbSet<sice_partidos_politicos> sice_partidos_politicos { get; set; }
        public DbSet<sice_registro_votos> sice_registro_votos { get; set; }
        public DbSet<sice_usuarios> sice_usuarios { get; set; }
    }
}
