//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sice_configuracion_rp
    {
        public int id { get; set; }
        public Nullable<int> id_partido { get; set; }
        public Nullable<int> porcentaje { get; set; }
        public Nullable<double> valor { get; set; }
    }
}
