//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sice_candidaturas
    {
        public sice_candidaturas()
        {
            this.sice_candidatos = new HashSet<sice_candidatos>();
        }
    
        public int id { get; set; }
        public string nombre_candidatura { get; set; }
        public int titular { get; set; }
        public int estado { get; set; }
        public string fk_letra { get; set; }
        public Nullable<int> id_distrito { get; set; }
    
        public virtual ICollection<sice_candidatos> sice_candidatos { get; set; }
    }
}
