//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sice_candidatos
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string sexo { get; set; }
        public int fk_ocupacion { get; set; }
        public int fk_lugar_nacimiento { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string domicilio { get; set; }
        public int tiempo_residencia { get; set; }
        public string clave_elector { get; set; }
        public string seccion_electoral { get; set; }
        public string numero_emision { get; set; }
        public string OCR { get; set; }
        public string CIC { get; set; }
        public int fk_partido { get; set; }
        public Nullable<int> fk_cargo { get; set; }
        public string acta_nacimiento { get; set; }
        public string crede_ifne { get; set; }
        public string acep_candi { get; set; }
        public string soli_confor { get; set; }
        public string soli_reelec { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> revision { get; set; }
    
        public virtual sice_candidaturas sice_candidaturas { get; set; }
        public virtual sice_partidos_politicos sice_partidos_politicos { get; set; }
    }
}
