//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sice_casillas
    {
        public int id { get; set; }
        public Nullable<int> consecutivo_total { get; set; }
        public Nullable<int> consecutivo_municipio { get; set; }
        public Nullable<int> id_distrito_federal { get; set; }
        public string cabecera_federal { get; set; }
        public Nullable<int> id_distrito_local { get; set; }
        public Nullable<int> id_cabecera_local { get; set; }
        public Nullable<long> id_municipio { get; set; }
        public Nullable<int> seccion { get; set; }
        public string tipo_seccion { get; set; }
        public Nullable<int> padron_electoral { get; set; }
        public Nullable<int> lista_nominal { get; set; }
        public string casilla { get; set; }
        public string tipo_casilla { get; set; }
        public string domicilio { get; set; }
        public string ubicación { get; set; }
        public string referencia { get; set; }
    }
}
