//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sice_configuracion_recuento
    {
        public int id { get; set; }
        public string sistema { get; set; }
        public Nullable<int> id_distrito { get; set; }
        public Nullable<int> grupos_trabajo { get; set; }
        public Nullable<int> puntos_recuento { get; set; }
        public Nullable<double> horas_disponibles { get; set; }
        public string tipo_recuento { get; set; }
    }
}
